name: p
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.13.4+2
  equatable: ^1.2.0
  firebase_analytics: 5.0.16
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.4+3
  firebase_crashlytics: ^0.1.4+1
  flutter_credit_card: ^0.1.1
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.3
  flutter_bloc: ^6.0.1
  getwidget: ^1.1.0
  get_it: ^4.0.1
  http: ^0.12.0+4 
  package_info: ^0.4.0+16
  image_cropper: ^1.2.3
  image_downloader: ^0.19.2
  image_picker: ^0.6.7+7
  intl: ^0.16.1
  material_design_icons_flutter: ^4.0.5045
  money: ^0.2.1
  settings_ui: ^0.3.0
  shared_preferences: ^0.5.8
  timeago: ^2.0.26
  url_launcher: ^5.4.2
  uuid: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/