name: p
description: A new Flutter project.
publish_to: "none"
version: 1.2.9+129

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  advance_pdf_viewer: ^2.0.0
  algolia: ^1.0.1
  animated_splash_screen: ^1.1.0
  cloud_firestore: ^2.2.2
  confetti: ^0.5.5
  # crashlytics: ^0.0.2
  equatable: ^2.0.3
  excel:
  firebase_analytics: ^8.1.2
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  # firebase_crashlytics: ^2.0.6
  flutter_credit_card: ^2.0.0
  flutter_email_sender: ^5.0.1
  flutter_staggered_grid_view: ^0.4.0
  firebase_messaging: ^10.0.2
  firebase_storage: ^8.1.3
  flutter_bloc: ^7.0.1
  getwidget: ^2.0.2
  get_it:
  http: ^0.13.3
  package_info: ^2.0.2
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
  image_cropper: ^1.4.1
  image_downloader: ^0.30.0
  image_picker: ^0.8.1+1
  intl: ^0.17.0
  maps_launcher: ^2.0.0
  material_design_icons_flutter: ^4.0.5955
  money: ^0.2.1
  rxdart: ^0.27.1
  settings_ui: ^1.0.0
  shared_preferences: ^2.0.6
  table_calendar: ^3.0.0
  timeago: ^3.1.0
  tutorial_coach_mark: ^1.0.3
  url_launcher: ^6.0.7
  uuid:
  youtube_parser: ^2.0.0
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/privacy_policy.pdf
