name: p
description: A new Flutter project.
publish_to: "none"
version: 1.2.6+126

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  algolia: ^0.1.7
  animated_splash_screen: ^1.0.1
  cloud_firestore: ^0.13.4+2
  confetti: ^0.5.4+1
  equatable: ^1.2.5
  excel: ^1.1.5
  firebase_analytics: 5.0.16
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.4+3
  firebase_crashlytics: ^0.1.4+1
  flutter_credit_card: ^0.1.1
  flutter_mailer: ^1.0.1
  flutter_staggered_grid_view: ^0.3.2
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.3
  flutter_bloc: ^6.1.0
  getwidget: ^1.1.0
  get_it: ^4.0.1
  http: ^0.12.0+4
  package_info: ^0.4.0+16
  path_provider: ^1.6.24
  percent_indicator: "^2.1.7+2"
  image_cropper: ^1.2.3
  image_downloader: ^0.19.2
  image_picker: ^0.6.7+7
  intl: ^0.16.1
  maps_launcher: ^1.2.2+2
  material_design_icons_flutter: ^4.0.5045
  money: ^0.2.1
  rxdart: ^0.24.1
  settings_ui: ^0.3.0
  shared_preferences: ^0.5.8
  table_calendar: ^2.2.3
  timeago: ^2.0.26
  tutorial_coach_mark: ^0.5.1
  url_launcher: ^5.4.2
  uuid: 2.2.0
  youtube_parser: ^1.1.0
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
